---

- hosts: workstations
  become_user: root
  become: true
  gather_facts: false
  vars:
    e_employer_name: home
    e_employer_facts:
      a_dev_dir: "{{ a_dev_base_dir }}/personal"
      a_dev_repos:
        - https://github.com/peteches/tmux-continuum
        - https://github.com/peteches/ansible-playbooks
        - https://github.com/peteches/tmux-resurrect
      a_zsh_cdpaths:
        - "{{ a_dev_base_dir }}/personal"
      a_git_author: pete 'Peteches' McCabe
      a_git_email: pete@peteches.co.uk
      a_ssh_config:
        - pattern: Host mi-go.peteches.co.uk
          priority: 100
          directives:
            User: peteches
    e_employer_users:
      - name: peteches
        groups: wheel
        createhome: yes
        shell: /usr/bin/zsh
        state: present
        password: $6$rounds=656000$ZyIeDzuuXOQDPZYo$rU4o2j5yQ7hFo1HUsnVqlhEkNFDt4Csog317xFdfdpN4NFjHzrCtzfp9dBA50xvOyWeNHQxZ1ai1Pa7N5se0T.
  roles:
    - e_employer

- include: workstation-playbook.yml

