---
vm:
  name: owncloud
  type: xen
  vm_host: xen.peteches.co.uk
  fqdn: owncloud.vm.peteches.co.uk
  ram: 2046
  vcpus: 1
  bootorder: cn
  graphics: 1
  bios: seabios
  vifs:
    - type: ioemu
      bridge: virbr0
      model: e1000
      net:
        mac: 00:16:3e:e7:71:bf
        ip: 192.168.122.100
        netmask: 255.255.255.0
        gateway: 192.168.122.1
        nameserver: 192.168.122.1
  disks:
    - format: raw
      vdev: xvda
      access: rw
      name: owncloud_root
      vg: vg_xen
      size: 15360
    - format: raw
      vdev: xvdb
      access: rw
      name: owncloud_data
      vg: vg_xen
      size: 153600

local_tftp:
  label: owncloud
  kernel: centos/x86_64/vmlinuz
  append: initrd=centos/x86_64/initrd.img ks=http://xen.peteches.co.uk/ks/owncloud.cfg

# vhosts:
#   - "upstream php-handler":
#       server: "unix:/var/run/php5-fpm.sock"
#   - server:
#       domain: owncloud.peteches.co.uk
#       server_name: owncloud.peteches.co.uk
#       return: "301 https://$server_name$request_uri"
#       listen: 80
#   - server:
#       ssl_opts:
#         ssl_certificate /etc/pki/tls/certs/owncloud.peteches.co.uk.crt
#         ssl_certificate_key /etc/pki/tls/private/owncloud.peteches.co.uk.key
#       options:
#         - listen       443 ssl
#         - server_name  owncloud.peteches.co.uk
#         - root /var/www/owncloud
#         - access_log  /var/log/nginx/owncloud-access.log  main
#         - error_log   /var/log/nginx/owncloud-error.log
#         - rewrite ^/caldav(.*)$ /remote.php/caldav$1 redirect
#         - rewrite ^/carddav(.*)$ /remote.php/carddav$1 redirect
#         - rewrite ^/webdav(.*)$ /remote.php/webdav$1 redirect
#         - client_max_body_size 10G
#         - fastcgi_buffers 64 4K
#         - index index.php
#         - error_page 403 /core/templates/403.php
#         - error_page 404 /core/templates/404.php
#       locations:
#         "/":
#           - rewrite ^/.well-known/host-meta /public.php?service=host-meta last
#           - rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json last
#           - rewrite ^/.well-known/carddav /remote.php/carddav/ redirect
#           - rewrite ^/.well-known/caldav /remote.php/caldav/ redirect
#           - rewrite ^(/core/doc/[^\/]+/)$ $1/index.html
#           - try_files $uri $uri/ index.php
#         "~ ^(.+?\.php)(/.*)?$":
#           - try_files $1 = 404
#           - include fastcgi_params
#           - fastcgi_param SCRIPT_FILENAME $document_root$1
#           - fastcgi_param PATH_INFO $2
#           - fastcgi_param HTTPS on
#           - fastcgi_pass php-handler
#         "~* ^.+\.(jpg|jpeg|gif|bmp|ico|png|css|js|swf)$"
#           - expires 30d
#           - access_log off
#         "= /robots.txt":
#           - allow all
#           - log_not_found off
#           - access_log off


