---

dnsmasq_configs:
  - name: tftp
    dict:
      enable-tftp: true
      tftp-root: /var/lib/tftpboot/
      dhcp-boot: pxelinux.0
  - name: dhcp
    dict:
      dhcp-range: "{{ networks['build'].cidr | ipaddr('1') | ipaddr('address') }},{{ networks['build'].cidr | ipaddr('30') | ipaddr('address') }},12h"

